services:
  - type: web
    name: aethermind-chatbot
    env: python
    buildCommand: pip install -r chatbot/requirements.txt
    startCommand: cd chatbot && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: MODEL_NAME
        value: llama-3.1-70b-versatile
      - key: TEMPERATURE
        value: 0.7
      - key: MAX_TOKENS
        value: 1024
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        sync: false